language: c
before_install:
    - sudo apt-get install -qq cmake
    - wget https://github.com/google/googletest/archive/release-1.6.0.zip
    - unzip release-1.6.0.zip
    - pushd googletest-release-1.6.0
    - cmake -DCMAKE_BUILD_TYPE=Release
    - make
    - sudo cp libgtest* /usr/lib
    - sudo mkdir /usr/include/gtest
    - sudo cp -r include/gtest/* /usr/include/gtest
script:
    - cmake -DCMAKE_BUILD_TYPE=Release ./
    - make
    - make test
